server:
  port: 8081
  address: 0.0.0.0
spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/card-db
    username: postgres
    password: card_password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yml

jwt:
  secret: q6b+8X0O8zIYFhG4u4n5nJ3hK9x9m9QWm6H6xW9f0uI=
  expiration: 86400000 # 24h

AES-256-key: T5j8B2k9M4g7Z1h3S4x9C0==
