server:
  port: 8081
  address: 0.0.0.0
spring:
  mvc:
    static-path-pattern: /**
  web:
    resources:
      static-locations:
        - classpath:/static/
        - classpath:/META-INF/resources/
  datasource:
    url: jdbc:postgresql://sqlcont:5432/card-db
    username: postgres
    password: card_password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yml

jwt:
  secret: q6b+8X0O8zIYFhG4u4n5nJ3hK9x9m9QWm6H6xW9f0uI=
  expiration: 86400000 # 24h

AES-256-key: 6bc1bee22e409f96e93d7e117393172a

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    url: /v3/api-docs
    enabled: true
logging:
  level:
    root: INFO
    com.poptsov: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE